### ISSUE TITLE
Needs support for CallableStatements

### ISSUE THREAD

**Issue by sepatel** [andrewoma/kwery#10]
I noticed that I needed to call an Oracle Stored Procedure (would be nice to have a dialect for Oracle) and this framework had no support for doing it. I had to resort to obtaining the native connection and writing java style code to make it happen.

Would be really nice if you added support for CallableStatements so that they work roughly the same way as your select/update statements do. I also didn't see it on the roadmap either.

**Comment by andrewoma** [comment]
Hi Sejal,

Neither Oracle support or stored procedures are on there roadmap for now. I was going to add an Oracle dialect but it's a pain provision for testing. 

As for stored procedures I have no immediate need and am not sure how simple it is to provide a common interface to all dialects.

Cheers
Andrew

**Comment by sepatel** [comment]
Alright, I'll go ahead and close this issue then. I've gone ahead and written my own jdbc extension layer to support the needs of jdbc sql usage (tekniq-jdbc) in the kotlin idiom. No where near the features you have put in but it gets the required job done nicely.

Thanks,
