### ISSUE TITLE
Is kwery supports async interface ?

### ISSUE THREAD

**Issue by tinycedar** [andrewoma/kwery#13]
With the release of Kotlin coroutine, we're able to write concurrently executed coroutines even within the same thread. So I am wondering whether kwery supports async inteface or not ?

**Comment by andrewoma** [comment]
No it doesn't. Nor are there really any plans to support it. The JDBC drivers are all synchronous so such an implementation would have to use a thread pool underneath.

If async JDBC drivers appear then it would be considered.
