### ISSUE TITLE
Dialects (e. g. PostgresDialect) may be objects (singletons)

### ISSUE THREAD

**Issue by Miha-x64** [andrewoma/kwery#17]
Why Dialects are represented by `open` classes? Does implementation inheritance really makes sense here? If no, then Dialects encapsulate no state and thus can be converted to 'object declarations' (singletons).

**Comment by andrewoma** [comment]
They certainly could be singletons. They're open with the idea of tweaking things like a MySQL5.7 variant of MySQL, but this could be achieved in other ways.
