### ISSUE TITLE
Bug when saving a field: String containing '$'

### ISSUE THREAD

**Issue by kloudsamurai** [andrewoma/kwery#6]
Looks like there's an insidious bug where Kotlin is interpreting a field containing a String with a dollar sign ($) as an actual token for replacement in bind parameters:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: No group 5
    at java.util.regex.Matcher.start(Matcher.java:375)
    at java.util.regex.Matcher.appendReplacement(Matcher.java:880)
    at com.github.andrewoma.kwery.core.DefaultSession.bindParameters(DefaultSession.kt:219)
```

Filling a String with any text containing '$' and performing an insert/update should recreate the issue. 

A quick study seems to indicate that we could fix this in MysqlDialect::bind().

**Comment by andrewoma** [comment]
Wow. Surprised I haven't hit it. I imagine it's in the logging code. Will get on it in the morning (3:30an) here

**Comment by andrewoma** [comment]
FYI, rhe parameter binding uses regular expressions under the covers so I'll have to escape dollar signs in the replacement bound value or the regex is treating it as a group.

**Comment by kloudsamurai** [comment]
Makes sense. LMK if you don't find time. I should have time to open a PR this weekend and definitely don't mind contributing. It's an awesome library. 

Now get some rest ;)

**Comment by andrewoma** [comment]
Fixed in https://github.com/andrewoma/kwery/commit/d901ddd6d403c0bb6dd36569d392f6ec4898ed22. Want me to push out a new release for this and the mysql auto increment issue?

**Comment by kloudsamurai** [comment]
That would be great -- when you have time. Thanks!
