### ISSUE TITLE
No magic. No proxies, interceptors or ....

### ISSUE THREAD

**Issue by mohsenk** [andrewoma/kwery#8]
Hi
you mentioned the kwery don't use Proxies or reflection  ... but you use Proxies in transactional project.
There isn't a better solution to implement this feature ?

Thanks.

**Comment by andrewoma** [comment]
Sure, there is a better solution - use `session.transaction { ... }`.

The transactional modules also steer you this direction in the READMEs:

> Note: the use of this module is discouraged - using a ThreadLocalSession with transaction blocks is preferred as they work without interceptor configuration.

The "trick" in making the `transaction` work as a replacement is making `transaction` blocks re-entrant. i.e. you can nest them and an inner block will join an existing transaction.

The other nice trick is using the transaction block as a single statement to the function body.

e.g.

```
fun myTransactionalFunction() = session.transaction {
}
```

This makes using it no worse than annotations - there's no additional nesting.

As such, I am thinking of dropping the transactional modules completely.

PS - the no proxies was really referring to proxying your domain objects, but take your point ;-)

**Comment by andrewoma** [comment]
FYI, I've updated the READMEs to document the info above
